# Generated by Django 3.0.3 on 2020-06-04 03:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccoladeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roster_year', models.IntegerField(null=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('accolade', models.CharField(max_length=20, null=True)),
                ('college', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BackUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, unique=True)),
                ('file', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('isCurrent', models.BooleanField(default=False)),
                ('isLoaded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, unique=True)),
                ('rosterData', models.FileField(null=True, upload_to='documents/')),
                ('starterData', models.FileField(null=True, upload_to='documents/')),
                ('accoladeData', models.FileField(null=True, upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('manual_upload', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GroupedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('home_town', models.CharField(max_length=30, null=True)),
                ('state_or_country', models.CharField(max_length=20, null=True)),
                ('high_school', models.CharField(max_length=100, null=True)),
                ('alternative_school', models.CharField(max_length=50, null=True)),
                ('college', models.CharField(max_length=50, null=True)),
                ('college_league', models.CharField(max_length=50, null=True)),
                ('highschoolcity', models.TextField(null=True)),
                ('highschoolstateorprovince', models.TextField(null=True)),
                ('highschoolcountry', models.TextField(null=True)),
                ('school_type', models.CharField(max_length=13, null=True)),
                ('starter_count', models.IntegerField(null=True)),
                ('accolade_count', models.IntegerField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('roster_year', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=None)),
                ('year', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, null=True), size=None)),
                ('position', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, null=True), size=None)),
                ('heights', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5, null=True), size=None)),
                ('weights', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=None)),
                ('bio_link', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='HighSchoolData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, null=True)),
                ('institution', models.CharField(max_length=100, null=True)),
                ('stateorprovince', models.CharField(max_length=20, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('school_type', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HighSchoolMatchMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roster_year', models.IntegerField(null=True)),
                ('player_number', models.CharField(max_length=10, null=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('year', models.CharField(max_length=10, null=True)),
                ('position1', models.CharField(max_length=20, null=True)),
                ('height', models.CharField(max_length=10, null=True)),
                ('weight', models.IntegerField(null=True)),
                ('home_town', models.CharField(max_length=30, null=True)),
                ('state_or_country', models.CharField(max_length=20, null=True)),
                ('high_school', models.CharField(max_length=100, null=True)),
                ('alternative_school', models.CharField(max_length=50, null=True)),
                ('college', models.CharField(max_length=50, null=True)),
                ('college_league', models.CharField(max_length=50, null=True)),
                ('bio_link', models.CharField(max_length=100, null=True)),
                ('is_starter', models.CharField(max_length=1, null=True)),
                ('accolade', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('institution', models.CharField(max_length=100, null=True)),
                ('stateorprovince', models.CharField(max_length=20, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('school_type', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RosterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roster_year', models.IntegerField(null=True)),
                ('player_number', models.CharField(max_length=10, null=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('year', models.CharField(max_length=10, null=True)),
                ('position1', models.CharField(max_length=20, null=True)),
                ('position2', models.CharField(max_length=20, null=True)),
                ('position3', models.CharField(max_length=10, null=True)),
                ('height', models.CharField(max_length=10, null=True)),
                ('weight', models.IntegerField(null=True)),
                ('home_town', models.CharField(max_length=30, null=True)),
                ('state_or_country', models.CharField(max_length=20, null=True)),
                ('high_school', models.CharField(max_length=100, null=True)),
                ('alternative_school', models.CharField(max_length=50, null=True)),
                ('college', models.CharField(max_length=50, null=True)),
                ('college_league', models.CharField(max_length=50, null=True)),
                ('bio_link', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StarterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roster_year', models.IntegerField(null=True)),
                ('number', models.IntegerField(null=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('potential_starts', models.IntegerField(null=True)),
                ('gp', models.IntegerField(null=True)),
                ('gs', models.IntegerField(null=True)),
                ('is_starter', models.CharField(max_length=1, null=True)),
                ('college', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
