# Generated by Django 3.0.3 on 2020-04-10 21:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccoladeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rosterYear', models.IntegerField()),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('accolade', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('homeTown', models.CharField(max_length=30)),
                ('stateOrCountry', models.CharField(max_length=20)),
                ('highSchool', models.CharField(max_length=100)),
                ('alternativeSchool', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=50)),
                ('collegeLeague', models.CharField(max_length=50)),
                ('highSchoolCity', models.TextField(null=True)),
                ('highSchoolSateOrProvince', models.TextField(null=True)),
                ('highSchoolCountry', models.TextField(null=True)),
                ('schoolType', models.CharField(max_length=13, null=True)),
                ('yearsStarter', models.IntegerField()),
                ('yearsAllConference', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('yearsOnRoster', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('yearsPlayed', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('positions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('heights', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=None)),
                ('weights', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('bioLinks', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='RosterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rosterYear', models.IntegerField()),
                ('playerNumber', models.CharField(max_length=10)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=10)),
                ('position1', models.CharField(max_length=20)),
                ('position2', models.CharField(max_length=20)),
                ('position3', models.CharField(max_length=10)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.IntegerField()),
                ('homeTown', models.CharField(max_length=30)),
                ('stateOrCountry', models.CharField(max_length=20)),
                ('highSchool', models.CharField(max_length=100)),
                ('alternativeSchool', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=50)),
                ('collegeLeague', models.CharField(max_length=50)),
                ('bioLink', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StarterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rosterYear', models.IntegerField()),
                ('number', models.IntegerField()),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('potentialStarts', models.IntegerField()),
                ('GP', models.IntegerField()),
                ('GS', models.IntegerField()),
                ('isStarter', models.CharField(max_length=1)),
                ('college', models.CharField(max_length=50)),
            ],
        ),
    ]
