# Generated by Django 3.0.3 on 2020-03-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschool',
            name='stateOrProvince',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='rostermasterdata',
            name='accolade',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='rostermasterdata',
            name='alternativeSchool',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='rostermasterdata',
            name='height',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='rostermasterdata',
            name='highSchool',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='rostermasterdata',
            name='homeTown',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='rostermasterdata',
            name='isStarter',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='rostermasterdata',
            name='playerNumber',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='rostermasterdata',
            name='stateOrCountry',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='rostermasterdata',
            name='weight',
            field=models.IntegerField(blank=True),
        ),
    ]
