# Generated by Django 3.0.3 on 2020-04-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschoolmatchmaster',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='highschoolmatchmaster',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='highschoolmatchmaster',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
