# Generated by Django 3.0.3 on 2020-04-10 22:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accoladedata',
            name='accolade',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accoladedata',
            name='college',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accoladedata',
            name='firstName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accoladedata',
            name='lastName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accoladedata',
            name='rosterYear',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='groupeddata',
            name='alternativeSchool',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='groupeddata',
            name='bioLinks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='groupeddata',
            name='college',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='groupeddata',
            name='collegeLeague',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='groupeddata',
            name='firstName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='groupeddata',
            name='heights',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='groupeddata',
            name='highSchool',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='groupeddata',
            name='homeTown',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='groupeddata',
            name='lastName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='groupeddata',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='groupeddata',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='groupeddata',
            name='positions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='groupeddata',
            name='stateOrCountry',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='groupeddata',
            name='weights',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=None),
        ),
        migrations.AlterField(
            model_name='groupeddata',
            name='yearsAllConference',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='groupeddata',
            name='yearsOnRoster',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=None),
        ),
        migrations.AlterField(
            model_name='groupeddata',
            name='yearsPlayed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='groupeddata',
            name='yearsStarter',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rosterdata',
            name='alternativeSchool',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rosterdata',
            name='bioLink',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rosterdata',
            name='college',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rosterdata',
            name='collegeLeague',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rosterdata',
            name='firstName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rosterdata',
            name='height',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rosterdata',
            name='highSchool',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rosterdata',
            name='homeTown',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rosterdata',
            name='lastName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rosterdata',
            name='playerNumber',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rosterdata',
            name='position1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rosterdata',
            name='position2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rosterdata',
            name='position3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rosterdata',
            name='rosterYear',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rosterdata',
            name='stateOrCountry',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rosterdata',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rosterdata',
            name='year',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='starterdata',
            name='GP',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='starterdata',
            name='GS',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='starterdata',
            name='college',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='starterdata',
            name='firstName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='starterdata',
            name='isStarter',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='starterdata',
            name='lastName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='starterdata',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='starterdata',
            name='potentialStarts',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='starterdata',
            name='rosterYear',
            field=models.IntegerField(null=True),
        ),
    ]
