# Generated by Django 3.0.3 on 2020-04-09 23:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('homeTown', models.CharField(max_length=30)),
                ('stateOrCountry', models.CharField(max_length=20)),
                ('highSchool', models.CharField(max_length=100)),
                ('alternativeSchool', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=50)),
                ('collegeLeague', models.CharField(max_length=50)),
                ('schoolType', models.CharField(max_length=13, null=True)),
                ('yearsStarter', models.IntegerField()),
                ('yearsAllConference', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('highSchoolCity', models.CharField(max_length=30, null=True)),
                ('highSchoolSateOrProvince', models.CharField(max_length=20, null=True)),
                ('highSchoolSateOrCountry', models.CharField(max_length=20, null=True)),
                ('yearsOnRoster', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('yearsPlayed', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('positions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('heights', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=None)),
                ('weights', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('bioLinks', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
            ],
        ),
    ]
