# Generated by Django 3.0.3 on 2020-04-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20200422_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighSchoolData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, null=True)),
                ('institution', models.CharField(max_length=100, null=True)),
                ('stateorprovince', models.CharField(max_length=20, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('school_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='highschoolmatchmaster',
            name='latitude',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='highschoolmatchmaster',
            name='longitude',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
