# Generated by Django 3.0.3 on 2020-03-13 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20200312_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highschool',
            old_name='instiution',
            new_name='institution',
        ),
    ]
