# Generated by Django 3.0.3 on 2020-04-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20200424_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschooldata',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='highschooldata',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='highschoolmatchmaster',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='highschoolmatchmaster',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
