# Generated by Django 3.0.3 on 2020-04-11 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20200410_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupeddata',
            old_name='postion',
            new_name='position',
        ),
    ]
