# Generated by Django 3.0.3 on 2020-04-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_groupeddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingSchools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='matchedhighschool',
            name='homeTown',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='matchedhighschool',
            name='matchedCity',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='matchedhighschool',
            name='matchedInstitution',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
