# Generated by Django 3.0.3 on 2020-04-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20200424_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschooldata',
            name='school_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
