# Generated by Django 3.0.3 on 2020-04-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20200411_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='document',
            new_name='accolateData',
        ),
        migrations.AddField(
            model_name='documents',
            name='rosterData',
            field=models.FileField(default=None, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documents',
            name='starterData',
            field=models.FileField(default=None, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
