# Generated by Django 3.0.3 on 2020-04-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20200409_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardingschools',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='boardingschools',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='boardingschools',
            name='name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardingschools',
            name='state',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
