# Generated by Django 3.0.3 on 2020-04-10 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20200409_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupeddata',
            old_name='highSchoolSateOrCountry',
            new_name='highSchoolCountry',
        ),
    ]
