# Generated by Django 3.0.3 on 2020-03-23 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_boardingschool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardingschool',
            old_name='state',
            new_name='address',
        ),
    ]
