# Generated by Django 3.0.3 on 2020-04-21 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20200415_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='accolateData',
            new_name='accoladeData',
        ),
    ]
