# Generated by Django 3.0.3 on 2020-04-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20200409_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardingschools',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
