# Generated by Django 3.0.3 on 2020-03-23 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20200323_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardingschool',
            old_name='address',
            new_name='state',
        ),
    ]
