# Generated by Django 3.0.3 on 2020-04-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20200421_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='sqlFile',
            field=models.FileField(default=None, upload_to='backups/'),
            preserve_default=False,
        ),
    ]
