# Generated by Django 3.0.3 on 2020-04-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20200424_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='description',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='description',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
