# Generated by Django 3.0.3 on 2020-05-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20200425_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='manual_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documents',
            name='accoladeData',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='rosterData',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='starterData',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
