# Generated by Django 3.0.3 on 2020-04-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_documents_sqlfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighSchoolMatchMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_number', models.CharField(max_length=10, null=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('roster_year', models.CharField(max_length=10, null=True)),
                ('position1', models.CharField(max_length=20, null=True)),
                ('height', models.CharField(max_length=10, null=True)),
                ('weight', models.IntegerField()),
                ('home_town', models.CharField(max_length=30, null=True)),
                ('state_or_country', models.CharField(max_length=20, null=True)),
                ('high_school', models.CharField(max_length=100, null=True)),
                ('alternative_school', models.CharField(max_length=50, null=True)),
                ('college', models.CharField(max_length=50, null=True)),
                ('college_league', models.CharField(max_length=50, null=True)),
                ('bio_link', models.CharField(max_length=100, null=True)),
                ('is_starter', models.CharField(max_length=1, null=True)),
                ('accolade', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('institution', models.CharField(max_length=100, null=True)),
                ('stateorprovince', models.CharField(max_length=20, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('school_type', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
