# Generated by Django 3.0.3 on 2020-05-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_auto_20200504_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='isCurrent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='backup',
            name='isLoaded',
            field=models.BooleanField(default=False),
        ),
    ]
