# Generated by Django 3.0.3 on 2020-04-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_highschoolmatchmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='highschoolmatchmaster',
            name='year',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='highschoolmatchmaster',
            name='roster_year',
            field=models.IntegerField(null=True),
        ),
    ]
