# Generated by Django 3.0.5 on 2020-05-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_auto_20200504_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='manual_upload',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
